using System.Text;
using System.Text.Json.Nodes;
using GsdOrchestrator.Mcp;
using GsdOrchestrator.Workflows.Models;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace GsdOrchestrator.Workflows.States;

/// <summary>
/// Auto-documents two things on the default branch (not the feature branch):
/// 1. docs/github-mcp-tools.md — regenerated from tools/list, no LLM needed
/// 2. CHANGELOG.md — prepended with a new entry for this workflow
/// If GSD_AUTO_MERGE=true, squash-merges the PR after documentation is done.
/// </summary>
public sealed class DocumentingState : IWorkflowState
{
    private readonly McpToolDispatcher _mcp;
    private readonly IChatClient _llm;
    private readonly bool _autoMerge;
    private readonly ILogger<DocumentingState> _logger;

    public WorkflowState State => WorkflowState.Documenting;

    public DocumentingState(McpToolDispatcher mcp, IChatClient llm, IConfiguration config, ILogger<DocumentingState> logger)
    {
        _mcp = mcp;
        _llm = llm;
        _autoMerge = string.Equals(config["GSD_AUTO_MERGE"], "true", StringComparison.OrdinalIgnoreCase);
        _logger = logger;
    }

    public async Task<GsdWorkflowContext> ExecuteAsync(GsdWorkflowContext ctx, CancellationToken ct)
    {
        var issue = ctx.Issue!;

        // Run both doc updates in parallel — they're independent
        await Task.WhenAll(
            UpdateMcpToolCatalogAsync(issue, ct),
            UpdateChangelogAsync(issue, ctx.Plan!, ctx.Edits!, ctx.PullRequest!, ctx.Issue!.DefaultBranch, ct));

        _logger.LogInformation("Documentation updated on {Branch}", issue.DefaultBranch);

        if (_autoMerge && ctx.PullRequest is not null)
            await AutoMergeAsync(issue, ctx.PullRequest, ct);

        return ctx.Transition(WorkflowState.Done);
    }

    // ── Auto-merge ───────────────────────────────────────────────────────────

    private async Task AutoMergeAsync(IssueContext issue, PullRequestContext pr, CancellationToken ct)
    {
        _logger.LogInformation("Auto-merging PR #{Number}", pr.PrNumber);
        try
        {
            await _mcp.CallAsync("merge_pull_request", new JsonObject
            {
                ["owner"] = issue.RepoOwner,
                ["repo"] = issue.RepoName,
                ["pullNumber"] = pr.PrNumber,
                ["merge_method"] = "squash",
                ["commit_title"] = pr.Title
            }, ct);
            _logger.LogInformation("PR #{Number} squash-merged", pr.PrNumber);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Auto-merge failed for PR #{Number} — continuing to Done", pr.PrNumber);
        }
    }

    // ── 1. MCP Tool Catalog ─────────────────────────────────────────────────

    private async Task UpdateMcpToolCatalogAsync(IssueContext issue, CancellationToken ct)
    {
        _logger.LogInformation("Refreshing docs/github-mcp-tools.md");

        var tools = await _mcp.ListToolsAsync(ct);
        var markdown = RenderToolCatalog(tools);

        await CommitFileAsync(
            issue, "docs/github-mcp-tools.md",
            markdown,
            $"docs: refresh GitHub MCP tool catalog [{DateTime.UtcNow:yyyy-MM-dd}]",
            issue.DefaultBranch,
            ct);
    }

    private static string RenderToolCatalog(IReadOnlyList<McpTool> tools)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# GitHub MCP Server — Tool Catalog");
        sb.AppendLine();
        sb.AppendLine($"> Auto-generated by GSD Orchestrator on {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine($"> Source: `@github/github-mcp-server` via `tools/list`");
        sb.AppendLine();
        sb.AppendLine($"**{tools.Count} tools available**");
        sb.AppendLine();
        sb.AppendLine("| Tool | Description |");
        sb.AppendLine("|---|---|");

        foreach (var tool in tools.OrderBy(t => t.Name))
            sb.AppendLine($"| `{tool.Name}` | {EscapeMarkdown(tool.Description)} |");

        sb.AppendLine();
        sb.AppendLine("## Tool Schemas");
        sb.AppendLine();

        foreach (var tool in tools.OrderBy(t => t.Name))
        {
            sb.AppendLine($"### `{tool.Name}`");
            sb.AppendLine();
            sb.AppendLine(tool.Description);
            sb.AppendLine();
            sb.AppendLine("<details><summary>Input schema</summary>");
            sb.AppendLine();
            sb.AppendLine("```json");
            sb.AppendLine(tool.InputSchema.ToJsonString(new() { WriteIndented = true }));
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("</details>");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string EscapeMarkdown(string s) =>
        s.Replace("|", "\\|").Replace("\n", " ");

    // ── 2. Changelog ────────────────────────────────────────────────────────

    private async Task UpdateChangelogAsync(
        IssueContext issue, AnalysisPlan plan, EditContext edits,
        PullRequestContext pr, string defaultBranch, CancellationToken ct)
    {
        _logger.LogInformation("Updating CHANGELOG.md");

        // Read existing changelog
        string existingContent = "";
        string existingSha = "";
        try
        {
            var existing = await _mcp.CallAsync("get_file_contents", new JsonObject
            {
                ["owner"] = issue.RepoOwner,
                ["repo"] = issue.RepoName,
                ["path"] = "CHANGELOG.md",
                ["ref"] = defaultBranch
            }, ct);
            var fileJson = existing.ParseInnerJson();
            existingSha = fileJson?["sha"]?.GetValue<string>() ?? "";
            var b64 = fileJson?["content"]?.GetValue<string>()?.Replace("\n", "") ?? "";
            existingContent = b64.Length > 0
                ? Encoding.UTF8.GetString(Convert.FromBase64String(b64))
                : "";
        }
        catch { /* CHANGELOG.md doesn't exist yet — will create */ }

        // Generate entry via LLM
        var entry = await GenerateChangelogEntryAsync(issue, plan, edits, pr, ct);

        // Prepend entry (keep existing content after the header if present)
        string newContent;
        if (existingContent.StartsWith("# Changelog"))
        {
            var afterHeader = existingContent["# Changelog".Length..].TrimStart();
            newContent = $"# Changelog\n\n{entry}\n\n{afterHeader}";
        }
        else if (existingContent.Length > 0)
        {
            newContent = $"# Changelog\n\n{entry}\n\n{existingContent}";
        }
        else
        {
            newContent = $"# Changelog\n\n{entry}\n";
        }

        await CommitFileAsync(
            issue, "CHANGELOG.md", newContent,
            $"docs: add changelog entry for #{issue.Number}",
            defaultBranch, ct, existingSha);
    }

    private async Task<string> GenerateChangelogEntryAsync(
        IssueContext issue, AnalysisPlan plan, EditContext edits,
        PullRequestContext pr, CancellationToken ct)
    {
        var filesChanged = string.Join(", ", edits.Edits.Select(e => $"`{e.Path}`"));
        var prompt = $"""
            Write a single CHANGELOG.md entry for the following change.
            Use Keep a Changelog format. Return only the entry text — no extra explanation.

            Issue #{issue.Number}: {issue.Title}
            Summary: {plan.Summary}
            Files changed: {filesChanged}
            PR: {pr.PrUrl}

            Example format:
            ## [Unreleased]
            ### Fixed
            - #42: Description of the fix ([#99]({pr.PrUrl}))
            """;

        var response = await _llm.GetResponseAsync(
            [new ChatMessage(ChatRole.User, prompt)],
            new ChatOptions { Temperature = 0.2f },
            ct);

        return (response.Text ?? $"- #{issue.Number}: {plan.Summary} ([PR]({pr.PrUrl}))").Trim();
    }

    // ── Shared ──────────────────────────────────────────────────────────────

    private async Task CommitFileAsync(
        IssueContext issue, string path, string content,
        string commitMessage, string branch, CancellationToken ct,
        string? existingSha = null)
    {
        var args = new JsonObject
        {
            ["owner"] = issue.RepoOwner,
            ["repo"] = issue.RepoName,
            ["path"] = path,
            ["message"] = commitMessage,
            ["content"] = Convert.ToBase64String(Encoding.UTF8.GetBytes(content)),
            ["branch"] = branch
        };

        if (!string.IsNullOrEmpty(existingSha))
            args["sha"] = existingSha;
        else
        {
            // Try to get current SHA for idempotency
            try
            {
                var cur = await _mcp.CallAsync("get_file_contents", new JsonObject
                {
                    ["owner"] = issue.RepoOwner, ["repo"] = issue.RepoName,
                    ["path"] = path, ["ref"] = branch
                }, ct);
                var sha = cur.ParseInnerJson()?["sha"]?.GetValue<string>();
                if (sha is not null) args["sha"] = sha;
            }
            catch { /* file doesn't exist yet */ }
        }

        await _mcp.CallAsync("create_or_update_file", args, ct);
        _logger.LogInformation("Committed {Path} on {Branch}", path, branch);
    }
}
