name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: Coding-Autopilot-System/.github/.github/workflows/release-please-reusable.yml@320a99a4c15487786dc73827ba7416303ab3fd1b
    secrets:
      release-please-token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
